### ISSUE TITLE
SpokestackTTSClient with connection issue

### ISSUE THREAD

**Issue by hannesa2** [spokestack/app-actions-example#5] opened 2021-04-16 13:35 UTC
I see in logcat this. 

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/3314607/115032027-21589280-9ec9-11eb-85db-eb4c07883d0d.png">

Maybe it's on of the reason, why I can't do anything with it ?

**Comment by space-pope** [comment] 2021-04-16 15:24
Hm, I have seen similar problems with OKHttp in the past, but not recently. Are you testing on a physical device or an emulator? If a physical device, what model/Android version; if the emulator, which API version are you running against?

**Comment by hannesa2** [comment] 2021-04-16 15:42
Both. First on my normal used Emulator. To verify, I did it on a real device too with same message

**Comment by space-pope** [comment] 2021-04-16 15:49
What version(s) of Android are you on?

BTW, you won't be able to properly test voice interactions on the emulator, as it doesn't properly integrate the microphone.

**Comment by hannesa2** [comment] 2021-04-16 16:44
> it doesn't properly integrate the microphone.

Audo-in/out works on Emulator https://github.com/741g/android-emulator-m1-preview/issues/10#issuecomment-773532762

**Comment by space-pope** [comment] 2021-04-16 16:46
Oh, bleeding edge support. Thanks for the pointer—that's great; I'd love to take all those notices out of our documentation when it makes it mainstream.

**Comment by hannesa2** [comment] 2021-04-16 16:46
> What version(s) of Android are you on?

Android 11 on Emulator and on Pixel 4

**Comment by space-pope** [comment] 2021-04-16 16:59
OK, so the problem certainly isn't due to device age :). I can't reproduce it locally, though, on either an Android 10 Pixel or 11 Pixel 3. Could you try out one of our other sample repositories—maybe the example app included in [Spokestack Tray](https://github.com/spokestack/spokestack-tray-android) or our [Minecraft skill port](https://github.com/spokestack/minecraft-skill-android)?

OKHttp is a dependency of the core library, so there shouldn't be any difference in behavior, but I want to make sure.

**Comment by space-pope** [comment] 2021-04-30 15:39
These OKHttp logs are addressed by the latest release of the core Spokestack library, merged in #8 .

**Closed as completed by space-pope** 2021-04-30 15:39 UTC
